# Numpy Basics

In [2]:
import numpy as np

## Arrays

In [3]:
arr = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [4]:
arr

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [5]:
arr * 5

array([[  7.5,  -0.5,  15. ],
       [  0. , -15. ,  32.5]])

In [6]:
arr.shape

(2, 3)

In [7]:
arr.dtype

dtype('float64')

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr2 = np.array(data2)

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(3, 4)

In [18]:
np.ones(10) * 3 + 4

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [19]:
np.zeros(10) * 3 + 4

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [21]:
np.empty((2, 3, 2)).shape

(2, 3, 2)

In [23]:
np.arange(5)

array([0, 1, 2, 3, 4])

There are types 'float64' and 'int32' and others. On can cast type with astype.

In [24]:
arr.dtype

dtype('float64')

In [25]:
arrint = arr.astype(np.int64)

In [26]:
arrint.dtype

dtype('int64')

## Slicing arrays

In [49]:
np.arange(3*4*5).reshape((3,4,5))[0:2]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [48]:
np.arange(3*4*5).reshape((3,4,5))[0:2,2:4]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [50]:
np.arange(3*4*5).reshape((3,4,5))[0:2,2:4, 1:3]

array([[[11, 12],
        [16, 17]],

       [[31, 32],
        [36, 37]]])

In [53]:
np.arange(3*4*5).reshape((3,4,5))[0:2,2:4, 1:3].reshape((2,4))

array([[11, 12, 16, 17],
       [31, 32, 36, 37]])

So with dimension we have (the naive dimension, the dimensions of each of the naive_dimension objects, etc...)